
name: Automation Assignment workflow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running test automation framework
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
    - name: Upload test log
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with: 
       name: Test logs
       path: logs/
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with: 
       name: Test Reports
       path: report.html
    - name: Test execution status
      run: echo "Test execution completed"
